version: '3'

services:
  frontend:
    image: 192.168.0.191:5000/subaipro/frontend:latest
    build: .
    command: npm run start
    ports:
      - "7777:3000"
    depends_on:
      - api

  redis:
    image: redis
  api:
    image: 192.168.0.191:5000/subaipro/backend:latest
    build:
      context: ./server/
    command: waitress-serve --host 0.0.0.0 --port 8080 generate_subs:app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    volumes:
      - outputs:/outputs
      - uploads:/uploads
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_BACKEND_URL=redis://redis:6379
      - OUTPUT_FOLDER=/outputs
      - UPLOAD_FOLDER=/uploads
      - BUILD_MODE=PROD

  celery-worker:
    image: 192.168.0.191:5000/subaipro/backend:latest
    command: celery -A generate_subs.celery worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - outputs:/outputs
      - uploads:/uploads
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_BACKEND_URL=redis://redis:6379
      - OUTPUT_FOLDER=/outputs
      - UPLOAD_FOLDER=/uploads
      - BUILD_MODE=PROD

volumes:
  outputs:
  uploads:
